# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(Major).$(Minor).$(Patch)-$(rev:r).$(Build.SourceBranchName)

trigger:
- master
- feature/*

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: buildConfiguration
  value: 'Release'
- group: csharp-vesync variables
- name: Major
  value: '1'
- name: Minor
  value: '0'
- name: Patch
  value: '3'

steps:
- task: FileTransform@1
  displayName: Substitute test appesttings variables
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/tests/VesyncApiIntegrationTests/'
    fileType: 'json'
    targetFiles: 'appsettings.json'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: Pack nuget pre-release
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: 'pack'
    packagesToPack: 'src/CSharpVesync/CSharpVesync.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Build.BuildNumber'
    includeSymbols: true

- task: DotNetCoreCLI@2
  displayName: Pack nuget release
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: 'pack'
    packagesToPack: 'src/CSharpVesync/CSharpVesync.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'byBuildNumber'
    includeSymbols: true
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'

- task: DotNetCoreCLI@2
  displayName: push nugets
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '/f96a5445-515b-4612-b7ca-dc39060e3bcd'